Allow setting requests timeout
ORCID/python-orcid pull request #24
Opened 2018-04-24 10:13 UTC by michamos

It is recommended by the [`requests` documentation](http://docs.python-requests.org/en/master/user/quickstart/#timeouts) to always set timeouts in production code:
> You can tell Requests to stop waiting for a response after a given number of seconds with the timeout parameter. Nearly all production code should use this parameter in nearly all requests.

This PR allows setting a timeout when instanciating the API.

2018-04-24 11:32 UTC, turtle321 commented on orcid/orcid.py
> +        PublicAPI.__init__(self, institution_key, institution_secret, sandbox,
Use `super(MemberAPI, self).__init__(...)` to make it work properly, also with multiple inheritance.

2018-04-24 11:32 UTC, turtle321 commented on orcid/orcid.py
> +                 timeout=None):
Another idea would be to have a parameter here like `requests_kwargs`: a dictionary that holds all parameters you want to pass to the actual `requests` calls. In the current use case we only have `timeout`, but future use cases might include proxies, headers, authentication and such.

2018-04-24 11:54 UTC, turtle321 commented on orcid/orcid.py
> +                 timeout=None):
Let's not do this now, but keep it in mind.

2018-04-24 12:54 UTC, MSusik commented on orcid/orcid.py
> +                 timeout=None):
Indeed, `kwargs` will be a better solution

2018-04-24 13:43 UTC, turtle321 commented on orcid/orcid.py
> +                 timeout=None):
We discussed internally, the change is not as easy as it seems (suppose you get a `headers` dict or another list arg, then you should properly merge the content with the one already used in the code). Also, a better way of doing this is using hooks, that would let us configure a specific requests rather than all of them with the same config.

I suggest to go with this change now and for the better change later on when we have that use case (we have opened a user story for it).

2018-04-26 20:00 UTC, turtle321 commented on orcid/orcid.py
> +        super(MemberAPI, self).__init__(self, institution_key,
Remove the self in the init: `super(MemberAPI, self).__init__(institution_key, ...)`

2018-04-27 11:16 UTC, michamos commented on orcid/orcid.py
> +        super(MemberAPI, self).__init__(self, institution_key,
done

2018-04-30 09:10 UTC, MSusik commented
I will take care of this PR this week.

Thanks a lot for contributing!

2018-05-02 08:26 UTC, MSusik requested changes
Please change only the lines that have to be changed. Other than that, the PR is good to go.

2018-05-02 08:26 UTC, MSusik commented on orcid/orcid.py
> +        The ORCID key given to the institution
I prefer indented continuations and I do not see a reason to change all the comments in the project within this PR.

2018-05-02 08:26 UTC, MSusik commented on orcid/orcid.py
> +            and put_code is not None and not isinstance(put_code, list):
Another time, no reason to change code. I assume your IDE must have changed it automatically. Please revert to the original version

2018-05-02 08:35 UTC, michamos commented on orcid/orcid.py
> +        The ORCID key given to the institution
Sure, didn't notice this happened.

2018-05-02 08:41 UTC, michamos commented
@MSusik I addressed your formatting issues.

2018-05-02 09:06 UTC, merged

2018-05-02 09:35 UTC, MSusik commented
@michamos You can install the library with the change from PyPI: 1.0.2 release

2018-05-02 09:36 UTC, michamos commented
:+1: Thanks for the quick release!